OUT = mathml.js

FILES = mouseover.js \
	token.js \
	assumptions.js \
	op-plus.js \
	op-minus.js \
	op-times.js \
	op-div.js \
	op-frac.js \
	op-root.js \
	op-pow.js \
	dblclick.js \
	contextmenu.js \
	core.js

build: ${FILES}
	cat ${FILES} > ${OUT}
